import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

import { generatePassword } from '../utils/util'

const Home: NextPage = () => {
  const [password, setPassword] = useState<string>('')
  const [size, setSize] = useState<number>(8)
  const [haveUppercase, setHaveUppercase] = useState<boolean>(true)
  const [haveLowercase, setHaveLowercase] = useState<boolean>(false)
  const [haveNumber, setHaveNumber] = useState<boolean>(true)
  const [haveSymbol, setHaveSymbol] = useState<boolean>(true)
  
  useEffect(() => {
    const pass = generatePassword(size, haveUppercase, haveLowercase, haveNumber, haveSymbol)
    setPassword(pass)
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-red-600 font-bold underline">
        Hello world!
      </h1>
      <p>{password}</p>
    </div>
  )
}

export default Home
