import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

import { generatePassword } from '../utils/util'

const Home: NextPage = () => {
  const [password, setPassword] = useState<string>('')
  
  useEffect(() => {
    const pass = generatePassword()
    setPassword(pass)
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-red-600 font-bold underline">
        Hello world!
      </h1>
      <p>{password}</p>
    </div>
  )
}

export default Home
